apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: devnginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - name: devnginx
        image: ec2-43-201-146-232.ap-northeast-2.compute.amazonaws.com/u05-project/web03:latest
        imagePullPolicy: Always

